-- AlterTable
ALTER TABLE "DeliveryProduct" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "deliveredQuantity" SET DEFAULT 0,
ALTER COLUMN "deliveredQuantity" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "returnedQuantity" SET DEFAULT 0,
ALTER COLUMN "returnedQuantity" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "OrderItem" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "StockMovement" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(65,30);
